baseURL = 'https://ron1tk.github.io/'
languageCode = 'en-us'
title = 'Ronit Kapoor'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "Ronit Kapoor"
description = "ML Researcher & Computer Science Graduate Student at Brown University"
author = "Ronit Kapoor"
DateFormat = "January 2, 2006"
defaultTheme = "auto"



ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
UseHugoToc = true
disableSpecial1stPost = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.profileMode]
enabled = true
title = "Ronit Kapoor"
subtitle = "ML Researcher | Brown University Sc.M."
imageUrl = "/images/image.png"
imageWidth = 200
imageHeight = 200
imageTitle = "Ronit Kapoor"


[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Research"
url = "/posts"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ron1tk"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/ronit-kapoor-profile"

[[params.socialIcons]]
name = "email"
url = "mailto:rkapoor@wpi.edu"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "research"
name = "Research"
url = "/posts/"
weight = 40