
baseURL = 'https://ron1tk.github.io/'
languageCode = 'en-us'
title = 'Ronit Kapoor'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
title = "Ronit Kapoor"
description = "Ronit Kapoor's Portfolio & Blog"
author = "Ronit Kapoor"
DateFormat = "January 2, 2006"
defaultTheme = "auto"

ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
UseHugoToc = true
disableSpecial1stPost = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.profileMode]
enabled = true
title = "Ronit Kapoor"
subtitle = "Developer & Student"
imageUrl = ""
imageWidth = 120
imageHeight = 120
imageTitle = "Ronit Kapoor"

[[params.profileMode.buttons]]
name = "Projects"
url = "/projects"

[[params.profileMode.buttons]]
name = "Posts"
url = "/posts"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ron1tk"

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/yourprofile"

[[params.socialIcons]]
name = "email"
url = "mailto:your.email@example.com"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 30

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 40